apiVersion: v1
kind: Service
metadata:
  name: svc-check-block-level-mainnet
spec:
  selector:
    app: check-block-level-mainnet
  ports:
    - protocol: TCP
      port: 80
      name: http
      targetPort: 8091
